# Generated by Django 5.2.6 on 2026-06-08 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EduForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EduProgramAdvantageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название преимущества')),
                ('text', models.TextField(verbose_name='Описание преимущества')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('academic_degree', models.CharField(blank=True, max_length=255, verbose_name='Ученая степень')),
                ('academic_title', models.CharField(blank=True, max_length=255, verbose_name='Ученое звание')),
                ('other_post', models.CharField(blank=True, max_length=255, verbose_name='Иные должности')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('spin_rinz', models.CharField(blank=True, max_length=255, verbose_name='SPIN-РИНЦ')),
                ('orcid', models.CharField(blank=True, max_length=255, verbose_name='ORCID')),
                ('prof_interests', models.TextField(blank=True, verbose_name='Проф.интересы')),
                ('expirience', models.TextField(blank=True, verbose_name='Опыт')),
                ('achivements', models.TextField(blank=True, verbose_name='Достижения')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('prof_dev', models.TextField(blank=True, verbose_name='Повышение квалификации')),
                ('projects', models.TextField(blank=True, verbose_name='Учатие в проектах')),
            ],
        ),
        migrations.CreateModel(
            name='Institut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название института')),
            ],
        ),
        migrations.CreateModel(
            name='KeySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Чему научитесь')),
            ],
        ),
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Перспективы трудоустройства')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Кем будете работать')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название профиля')),
                ('text', models.TextField(verbose_name='Что будете изучать')),
            ],
        ),
        migrations.CreateModel(
            name='Suitable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Кому подходит программа')),
            ],
        ),
        migrations.CreateModel(
            name='EduProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('edu_number', models.CharField(max_length=100, verbose_name='Шифр')),
                ('level', models.CharField(choices=[('Бакалавриат', 'Bachelor'), ('Магистратура', 'Magister'), ('Специалитет', 'Specialty'), ('Аспирантура', 'Aspirant')], max_length=100)),
                ('about_program', models.TextField(verbose_name='О программе')),
                ('exam_ege', models.TextField(verbose_name='Экзамены ЕГЭ')),
                ('exam_spo', models.TextField(verbose_name='Экзамены СПО')),
                ('advantage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education.eduprogramadvantagetext', verbose_name='Преимущество')),
            ],
        ),
        migrations.CreateModel(
            name='EduProgramEduForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lerning_time', models.CharField(max_length=100)),
                ('budget_places', models.IntegerField()),
                ('contract_places', models.IntegerField()),
                ('edu_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.eduforms')),
                ('edu_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.eduprogram')),
            ],
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='edu_form',
            field=models.ManyToManyField(through='education.EduProgramEduForm', to='education.eduforms'),
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кафедры')),
                ('about', models.TextField(blank=True, verbose_name='О кафедре')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('about_employees', models.TextField(blank=True)),
                ('science_info', models.TextField(blank=True)),
                ('practice_info', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('tasks', models.TextField(blank=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='education.employee', verbose_name='Заведующий')),
                ('employees', models.ManyToManyField(to='education.employee')),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.institut')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название дисциплины')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kafedra', to='education.kafedra')),
            ],
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='key_skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education.keyskills', verbose_name='Чему научитесь'),
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='perspective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education.perspective', verbose_name='Перспективы трудоустройства'),
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education.position', verbose_name='Кем будете работать'),
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='program_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education.programstructure', verbose_name='Что будете изучать'),
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='suitable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education.suitable', verbose_name='Кому подходит'),
        ),
    ]
