# Generated by Django 5.2.6 on 2026-06-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduprogram',
            name='edu_card_img',
            field=models.ImageField(default=0, upload_to='edu_program_images/', verbose_name='Изображение карточки ОП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='edu_prog_advantage_img',
            field=models.ImageField(default=0, upload_to='edu_program_images/', verbose_name='Изображение блока преимуществ ОП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='edu_prog_banner_img',
            field=models.ImageField(default=0, upload_to='edu_program_images/', verbose_name='Изображение баннера ОП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='edu_prog_perspective_img1',
            field=models.ImageField(default=0, upload_to='edu_program_images/', verbose_name='Изображение1 блока перспектив ОП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='edu_prog_perspective_img2',
            field=models.ImageField(default=0, upload_to='edu_program_images/', verbose_name='Изображение2 блока перспектив ОП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='edu_prog_perspective_img3',
            field=models.ImageField(default=0, upload_to='edu_program_images/', verbose_name='Изображение3 блока перспектив ОП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='edu_prog_structure_img',
            field=models.ImageField(default=0, upload_to='edu_program_images/', verbose_name='Изображение блока структуры ОП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='kafedra_card_img',
            field=models.ImageField(default=0, upload_to='kafedra_images/', verbose_name='Изображение кафедры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='kafedra_name',
            field=models.CharField(default=0, max_length=255, verbose_name='Выпускающая кафедра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='kafedra_url',
            field=models.URLField(default=0, max_length=255, verbose_name='Ссылка на страницу кафедры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='karedra_tags',
            field=models.TextField(default=0, verbose_name='Теги кафедры'),
            preserve_default=False,
        ),
    ]
