# Generated by Django 4.2.24 on 2026-06-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_eduprogram_edu_card_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='eduforms',
            options={'verbose_name': 'Форма обучения'},
        ),
        migrations.AlterModelOptions(
            name='eduprogram',
            options={'verbose_name': 'Образовательная программа', 'verbose_name_plural': 'Образовательные программы'},
        ),
        migrations.AlterModelOptions(
            name='eduprogramadvantagetext',
            options={'verbose_name': 'Преимущества ОП', 'verbose_name_plural': 'Преимущества ОП'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='institut',
            options={'verbose_name': 'Институт', 'verbose_name_plural': 'Институты'},
        ),
        migrations.AlterModelOptions(
            name='kafedra',
            options={'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AlterModelOptions(
            name='keyskills',
            options={'verbose_name': 'Ключевые навыки', 'verbose_name_plural': 'Ключевые навыки'},
        ),
        migrations.AlterModelOptions(
            name='perspective',
            options={'verbose_name': 'Перспективы', 'verbose_name_plural': 'Перспективы '},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Кем работать', 'verbose_name_plural': 'Кем работать'},
        ),
        migrations.AlterModelOptions(
            name='programstructure',
            options={'verbose_name': 'Структура ОП', 'verbose_name_plural': 'Структура ОП'},
        ),
        migrations.AlterModelOptions(
            name='suitable',
            options={'verbose_name': 'Кому подходит', 'verbose_name_plural': 'Кому подходит'},
        ),
        migrations.RemoveField(
            model_name='eduprogram',
            name='kafedra_card_img',
        ),
        migrations.RemoveField(
            model_name='eduprogram',
            name='kafedra_url',
        ),
        migrations.RemoveField(
            model_name='eduprogram',
            name='karedra_tags',
        ),
        migrations.RemoveField(
            model_name='kafedra',
            name='about',
        ),
        migrations.RemoveField(
            model_name='kafedra',
            name='about_employees',
        ),
        migrations.RemoveField(
            model_name='kafedra',
            name='director',
        ),
        migrations.RemoveField(
            model_name='kafedra',
            name='email',
        ),
        migrations.RemoveField(
            model_name='kafedra',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='kafedra',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='kafedra',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='kafedra',
            name='practice_info',
        ),
        migrations.RemoveField(
            model_name='kafedra',
            name='science_info',
        ),
        migrations.RemoveField(
            model_name='kafedra',
            name='tasks',
        ),
        migrations.AddField(
            model_name='kafedra',
            name='kafedra_card_img',
            field=models.ImageField(default='default_kaf.jpg', upload_to='kafedra_images/', verbose_name='Изображение кафедры'),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='kafedra_url',
            field=models.URLField(default='https://hgpurf.ru/', max_length=255, verbose_name='Ссылка на страницу кафедры'),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='karedra_tags',
            field=models.TextField(default=2, verbose_name='Теги кафедры'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eduprogram',
            name='kafedra_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education.kafedra', verbose_name='Выпускающая кафедра'),
        ),
        migrations.AlterField(
            model_name='eduprogrameduform',
            name='lerning_time',
            field=models.CharField(choices=[('4 года', 'Four'), ('4 года 6 месяцев', 'Four Half'), ('5 лет', 'Five'), ('5 лет 6 месяцев', 'Five Half')], max_length=100),
        ),
    ]
