# Generated by Django 4.2.24 on 2026-06-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_discipline_options_alter_eduforms_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kafedra',
            name='karedra_tags',
        ),
    ]
