# Generated by Django 4.2.24 on 2026-06-13 08:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_remove_kafedra_karedra_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduprogram',
            name='about_program',
            field=ckeditor.fields.RichTextField(verbose_name='О программе'),
        ),
    ]
