# Generated by Django 4.2.24 on 2026-06-13 10:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_eduprogram_about_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduprogram',
            name='about_program',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
