# Generated by Django 4.2.24 on 2026-06-13 10:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_eduprogram_about_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduprogram',
            name='about_program',
            field=ckeditor.fields.RichTextField(verbose_name='О программе'),
        ),
        migrations.AlterField(
            model_name='eduprogram',
            name='exam_ege',
            field=ckeditor.fields.RichTextField(verbose_name='Экзамены ЕГЭ'),
        ),
        migrations.AlterField(
            model_name='eduprogram',
            name='exam_spo',
            field=ckeditor.fields.RichTextField(verbose_name='Экзамены СПО'),
        ),
        migrations.AlterField(
            model_name='eduprogramadvantagetext',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Описание преимущества'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='achivements',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='expirience',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prof_dev',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Повышение квалификации'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prof_interests',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Проф.интересы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='projects',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Учатие в проектах'),
        ),
        migrations.AlterField(
            model_name='keyskills',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Чему научитесь'),
        ),
        migrations.AlterField(
            model_name='perspective',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Перспективы трудоустройства'),
        ),
        migrations.AlterField(
            model_name='position',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Кем будете работать'),
        ),
        migrations.AlterField(
            model_name='programstructure',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Что будете изучать'),
        ),
        migrations.AlterField(
            model_name='suitable',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Кому подходит программа'),
        ),
    ]
