# Generated by Django 4.2.24 on 2026-06-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_eduprogram_about_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eduprogram',
            name='advantage',
        ),
        migrations.RemoveField(
            model_name='eduprogram',
            name='key_skills',
        ),
        migrations.RemoveField(
            model_name='eduprogram',
            name='perspective',
        ),
        migrations.RemoveField(
            model_name='eduprogram',
            name='position',
        ),
        migrations.RemoveField(
            model_name='eduprogram',
            name='program_structure',
        ),
        migrations.RemoveField(
            model_name='eduprogram',
            name='suitable',
        ),
        migrations.AddField(
            model_name='eduprogramadvantagetext',
            name='op',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.eduprogram', verbose_name='ОП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyskills',
            name='op',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.eduprogram', verbose_name='ОП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perspective',
            name='op',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.eduprogram', verbose_name='ОП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='op',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.eduprogram', verbose_name='ОП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programstructure',
            name='op',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.eduprogram', verbose_name='ОП'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suitable',
            name='op',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.eduprogram', verbose_name='ОП'),
            preserve_default=False,
        ),
    ]
