# Generated by Django 4.2.24 on 2026-06-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_remove_eduprogram_advantage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eduprogrameduform',
            options={'verbose_name': 'Форма и период обучения', 'verbose_name_plural': 'Формы и периоды обучения'},
        ),
        migrations.AlterField(
            model_name='eduprogrameduform',
            name='lerning_time',
            field=models.CharField(choices=[('2 года', 'Two'), ('2 года 6 месяцев', 'Two Half'), ('3 года', 'Three'), ('4 года', 'Four'), ('4 года 6 месяцев', 'Four Half'), ('5 лет', 'Five'), ('5 лет 6 месяцев', 'Five Half')], max_length=100),
        ),
    ]
