# Generated by Django 4.2.24 on 2026-06-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_alter_eduprogrameduform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institut',
            name='institut_img',
            field=models.ImageField(blank=True, upload_to='institut_images/', verbose_name='Изображение института'),
        ),
        migrations.AddField(
            model_name='institut',
            name='institut_logo',
            field=models.ImageField(blank=True, upload_to='institut_images/', verbose_name='Лого института'),
        ),
        migrations.AddField(
            model_name='institut',
            name='institut_url',
            field=models.URLField(default='https://hgpurf.ru/', max_length=255, verbose_name='Ссылка на страницу института'),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='kafedra_logo',
            field=models.ImageField(blank=True, upload_to='kafedra_images/', verbose_name='Лого кафедры'),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='kafedra_url_max',
            field=models.URLField(default='https://hgpurf.ru/', max_length=255, verbose_name='Ссылка на чат в MAX'),
        ),
        migrations.AddField(
            model_name='kafedra',
            name='kafedra_url_tg',
            field=models.URLField(default='https://hgpurf.ru/', max_length=255, verbose_name='Ссылка на чат в ТГ'),
        ),
    ]
