# Generated by Django 4.2.24 on 2026-06-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_institut_institut_img_institut_institut_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedra',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
    ]
