# Generated by Django 4.2.24 on 2026-06-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_kafedra_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduprogram',
            name='edu_form',
            field=models.ManyToManyField(related_name='eduprogramseduform', through='education.EduProgramEduForm', to='education.eduforms'),
        ),
    ]
