# Generated by Django 4.2.24 on 2026-06-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_alter_eduprogram_edu_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduprogram',
            name='edu_form',
            field=models.ManyToManyField(through='education.EduProgramEduForm', to='education.eduforms'),
        ),
        migrations.AlterField(
            model_name='eduprogrameduform',
            name='edu_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eduprogramseduform', to='education.eduprogram'),
        ),
    ]
